"""empty message

Revision ID: 866b4465bb13
Revises: c27433c88c13
Create Date: 2023-10-28 17:10:08.606898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866b4465bb13'
down_revision = 'c27433c88c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=10000),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
